URL_SERVICES = "https://cnt-13e1f9b1-1b6d-4973-9a48-011284d59080.containerhub.tripleten-services.com"
DOCS_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
KIT_PATH = "/api/v1/kits"
KIT_TABLE_PATH = "/api/db/resources/kit_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
