URL_SERVICES = "https://cnt-29d00da0-d8ac-4f07-a3b8-3e846d66b9cf.containerhub.tripleten-services.com"
DOCS_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
KIT_PATH = "/api/v1/kits"
KIT_TABLE_PATH = "/api/db/resources/kit_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
