URL_SERVICES = "https://cnt-cd24de27-e3fe-4522-aa8b-5d1e26aebf8d.containerhub.tripleten-services.com"
DOCS_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
KIT_PATH = "/api/v1/kits"
KIT_TABLE_PATH = "/api/db/resources/kit_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
